language: node_js

node_js:
  - "5"
  
before_install:
#- sudo apt-get update -qq
- sudo rm -rf /usr/local/lib/node_modules/
- npm i -g npm@5.5.1
#- sudo apt remove nodejs npm
#- curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
#- sudo apt-get install -y nodejs
- npm install -g now

install:
- echo "Starting"
- ./scripts/deploy.sh
    
after_script: # here's a build step block
- echo "Cleaning up the mess..."

notifications: # set notification options
  email:
    recipients:
      - ze@iodrift.com
