language: node_js

before_install:
#- sudo apt-get update -qq
- npm i -g npm@latest
- npm install -g now

install:
- echo "Starting"
- ./scripts/deploy.sh
    
after_script: # here's a build step block
- echo "Cleaning up the mess..."

notifications: # set notification options
  email:
    recipients:
      - ze@iodrift.com
