language: node_js

before_install:
#- sudo apt-get update -qq
- npm i -g npm@4.6.1
#- sudo apt remove nodejs npm
#- curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
#- sudo apt-get install -y nodejs
- npm install -g now

install:
- echo "Starting"
- ./scripts/deploy.sh
    
after_script: # here's a build step block
- echo "Cleaning up the mess..."

notifications: # set notification options
  email:
    recipients:
      - ze@iodrift.com
